config/routes.rb
Rails.application.routes.draw do
  resources :lexicons
  resources :items
  resources :feeds
  root 'feeds#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  private

end

app/models/feed.rb
class Feed < ApplicationRecord

    has_many :items, dependent: :destroy
    validates :link, uniqueness: true

    def daily_total_vector
        self.items.average(:score)
    end

    def positive_vector
        self.items.where("score > '50'")
    end

    def negative_vector
        self.items.where("score < '50'")
    end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :feed
  before_save :datetime_to_epoch, :change_score_range

  private

  def datetime_to_epoch
    self.published_epoch = self.published_at.to_i
  end

  def change_score_range
    unless self.score.nil?
      number_to_convert = self.score
      scaleMin = -100
      scaleMax = 100
      probMin = 0
      probMax = 1
      percent = (number_to_convert - probMin)/(probMax - probMin)
      self.score = percent*(scaleMax - scaleMin) + scaleMin
    end
  end

end

app/models/lexicon.rb
class Lexicon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

    require 'rss'
    require 'open-uri'

    before_action :set_feed, only: [:show, :destroy]

    def index
        @feed = Feed.new
        @feeds = Feed.all
    end

    def create
        begin
            @feed = Feed.new(feed_params)
            @url = @feed.link
            open(@url) do |rss|
                data = RSS::Parser.parse(rss)
                @feed.title = data.channel.title
                @feed.description = data.channel.description
                @feed.copyright = data.channel.copyright
                if @feed.save
                    redirect_to root_path, notice: "Feed added."
                else
                    redirect_to root_path, notice: "Feed already exists."
                end
            end
        rescue
            redirect_to root_path, notice: "Error adding feed. Enter a valid RSS feed."
        end
    end

    def show
        @items = @feed.items.order('published_at DESC')
    end

    def destroy
        @feed.destroy
        redirect_to root_path
    end

    private

    def set_feed
        @feed = Feed.find(params[:id])
    end

    def feed_params
        params.require(:feed).permit(:link)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/lexicons_controller.rb
class LexiconsController < ApplicationController
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController

    def index
        @feed = Feed.new
        @feeds = Feed.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lexicons_helper.rb
module LexiconsHelper
end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/views/feeds/_feed.html.erb
<tr>
    <td>
        <%= feed.title %>
    </td>
    <td>
        <a href="<%= feed.link %>" target="_blank">RSS Link</a>&nbsp;&bull;&nbsp;
        <%= link_to 'View Feed Items', feed_path(feed) %>&nbsp;&bull;&nbsp;
        <%= link_to 'Delete Feed', feed_path(feed), method: :delete, data: { confirm: 'Are you sure you want to delete this feed?' } %>
    </td>
</tr>

app/views/feeds/index.html.erb
<div style="text-align: center;">
    <h1>Sentiment Statistics</h1>
    <h4>Sentiment range from -100 to 100, for each RSS feed item; negative to positive sentiment, respectively.</h4>
</div>

<br/>

<div style="text-align: center;">
    <%= scatter_chart Item.pluck(:published_epoch, :score), xtitle: "Time in Epoch", ytitle: "Sentiment Score" %>
    <br/>
    <%= line_chart @feeds.map { |feed|
        {name: "Positive Vector", data: feed.positive_vector }
    } %>
</div>

<hr/>

<div style="text-align: center;">
    <h1>Feed List</h1>
    <%= form_for @feed do |f| %>
        RSS URL: <%= f.text_field :link %>
    <%= f.submit "Add Feed" %>
    <% end %>
    <% unless flash[:notice].nil? %>
        <p><%= flash[:notice] %></p>
    <% end %>
</div>

<br/>

<div>
    <% unless @feeds.empty? %>
        <table style="margin: auto;">
            <thead>
                <th>Feed</th>
                <th>Actions</th>
            </thead>
            <tbody>
                <% @feeds.each do |feed| %>
                    <%= render partial: 'feeds/feed', locals: { feed: feed } %>
                <% end %>
            </tbody>
        </table>
    <% end %>
</div>

<br/>

app/views/feeds/show.html.erb
<div style="text-align: center;">
    <%= link_to 'Return to Feed List', feeds_path %>
</div>

<hr/>

<div style="text-align: center;">
    <h1><%= @feed.title %></h1>
    <h3><%= @feed.description %></h3>
    <h5><%= @feed.copyright.nil? ? "No copyright statement in RSS." :  @feed.copyright.html_safe %></h5>
</div>

<hr/>

<% @items.each do |item| %>
    <p><%= item.published_at %> --- <%= item.title %> --- <%= item.score %></p>
    <hr/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rssanalyzer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>